<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button-dinamis</name>
   <tag></tag>
   <elementGuidId>d3182a03-e2d1-49e5-9a84-e60078a1632c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name = 'recommend'][${index}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@name = 'recommend']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f536a4bc-a750-4010-8586-1526bd0650a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recommend</value>
      <webElementGuid>e7b6b719-1223-476d-87d3-3892984e8121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${actionButtonText}</value>
      <webElementGuid>2e69e61d-131c-4544-a0b6-6dfbbf14e7bb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
