<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>car-name</name>
   <tag></tag>
   <elementGuidId>812dfc7e-4b8b-4a13-87dc-fd37cc075d9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[@class = 'car-name' and (text() = '${carName}' or . = '${carName}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>cd4c4b84-ac30-4dac-99fc-957fc40bede1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>car-name</value>
      <webElementGuid>5613e622-bc4d-491f-a07c-50b20aaad9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${carName}</value>
      <webElementGuid>5590e3e3-4d15-448e-b567-d1f5a291b3ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
