<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>KKBSK P17</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a3a2e90e-fb0d-416e-bea0-ee01568885e3</testSuiteGuid>
   <testCaseLink>
      <guid>9f941d5c-8057-4718-adfd-4da07370fb6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cms/1. Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5812128-7869-41ce-b7ca-89d94ac6143e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>025197fb-e51c-48e6-b6a8-6a91c82361cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e95b1c5-ad67-4237-ab62-42f00a2b8c6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eeb0f37-5e5b-4fb6-b192-51e95a6924af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/cms/2. Master Event - Add</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>147d1993-0caa-4888-aaf1-54fccef6e989</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19e16f96-b79c-4a75-b270-f7712a77aa71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1911f89c-1409-494a-a481-f5a0a309aedd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95707712-4d09-42a4-a955-8f490ce445a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0ec3429-82fc-45c7-b41b-e64c3e7dfcbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36b46fd9-6292-4105-9d27-aea9d1d998da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dfb5200-1b4c-410a-a69c-3cd3f3f5ce9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e941dc2f-4ac1-4e39-bd68-32f821e288fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d8bb68f-355d-402a-a402-46cf8839f602</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9897e461-590d-4b15-830c-8d3d52ac27f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/cms/3. Search and Sorting - Master Event</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c46e3f-c18a-471e-ba38-3c904516ed16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25e475fe-46ec-4825-928b-4de2fbe02dfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fddb975-f3f9-466e-94c4-a8347fd373d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96bba7b1-aaec-4915-ab18-9d871a0ff986</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>435c0270-ad35-484c-80c8-10a42444c1f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c90a4a3d-eb6d-47c7-bb69-74bb3bfe697f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3499242d-a030-4a06-9e9b-a46397646fd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/cms/Cek Event</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2335d766-1b10-4efc-9a94-176e62e043e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7eb007a-3531-4e15-999c-e906c530e90b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>161f2e79-e7d3-44a5-84fa-82435c294a29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cms/event-kanwil/1. event-kanwil</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>48b0a1eb-ee41-460f-873c-3d3e077701bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cms/event-kanwil/2. verifikasi data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f38549d-237c-47f9-adc8-573cf2d5fc3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e1404ac-c343-45f6-a068-94696eb02c1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db3bec41-56f6-4c65-aff1-da97f1c19137</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cms/event-kanwil/3. edit data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4a32689-8210-4bd0-8351-265e583a49fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ebff385-4fec-4776-95fd-5013cdbe7094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>648a2933-b2b4-41c5-9d5f-40fbc830fbff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>657283c9-8371-4725-bfe5-9eeb3abb696b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cms/event-kanwil/4. verifikasi data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c02aa55-2519-48c7-81b5-3c0ae6a834c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a23f475-a395-466f-ae7e-05011ee735bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f0c8d9b-4f0e-4666-b02e-41fc29c44ae7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cms/event-kanwil/4. check sort</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59641b5b-f0d3-46ec-b69f-592072676a8b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
