<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown-simulasi</name>
   <tag></tag>
   <elementGuidId>1077fcec-071d-4f88-9358-b40006446284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>51ae97f5-730b-46df-a984-81eabb48e87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wilayah</value>
      <webElementGuid>3b931f98-0b61-413b-b6d8-9c4ae4417908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='${id}']//select[@name='${name}']</value>
      <webElementGuid>bfa17f2a-39cf-4397-9e68-06b1e060e7d5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
