<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldKontak</name>
   <tag></tag>
   <elementGuidId>75b87aae-1b3c-42a0-aec7-7e2abab55927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1478fec-d5b9-42fc-87e7-0fa8ed587dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>${fieldName}</value>
      <webElementGuid>eeeba8a3-5933-4706-94fc-9680818a5e43</webElementGuid>
   </webElementProperties>
</WebElementEntity>
