<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simulasi-field-dinamis</name>
   <tag></tag>
   <elementGuidId>71570680-57fa-4be7-8905-d6a37b60038d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;hargaDiskon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credit']/form/div/div/div/div/div/div/input[@name = 'hargaDiskon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82b553ba-9914-4861-9de2-8d34c9328935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca8fced2-1868-41ea-bad7-621b0cfc5d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control money</value>
      <webElementGuid>1f1acdb5-dcf3-46fd-ab14-f1d409cab71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hargaDiskon</value>
      <webElementGuid>9fa1d409-c9d3-4c43-b816-dc9662280ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2538000000</value>
      <webElementGuid>1139a265-d6a4-4041-a9af-3022ffb5d36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;${tipeSimulasi}&quot;)//input[@name=&quot;${name}&quot;]</value>
      <webElementGuid>36c0382e-6add-4afb-a143-65be4daef676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='hargaDiskon']</value>
      <webElementGuid>ab129e4d-51ff-497d-93e1-ffdf16158e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credit']/form/div/div/div/div/div/div/input[6]</value>
      <webElementGuid>f374baeb-151d-4435-b8ed-dfb38833d425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>b89216d6-a87a-47b8-84ed-0a0ccdbb6464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hargaDiskon']</value>
      <webElementGuid>48b50a67-1c8d-4d6a-a4b0-0abe6e46aef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
