<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xpath-object</name>
   <tag></tag>
   <elementGuidId>00eb4a24-5e10-4256-8ce7-526b9cd0d601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${xpath}</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${xpath}</value>
      <webElementGuid>b5d7aa70-ab3b-41fa-bb89-3911a46d8490</webElementGuid>
   </webElementProperties>
</WebElementEntity>
